use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use crate::load_order::ini_parser::{read_mod_list_ini, write_mod_list_ini};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergedFilePayload {
    pub relative_path: String, // e.g. "media/lua/client/ISUI/ISInventoryPane.lua"
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasterPatchRequest {
    pub user_zomboid_dir: String,
    pub mod_list_ini_path: String,
    pub merged_files: Vec<MergedFilePayload>,
    pub active_polyfill_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasterPatchResult {
    pub success: bool,
    pub patch_mod_dir: String,
    pub files_written: usize,
    pub polyfills_injected: usize,
}

/// Generates the synthetic master patch mod under Zomboid/mods/Z_PZModStudio_MergedPatch and updates ModListData.ini.
pub fn generate_master_patch(req: MasterPatchRequest) -> Result<MasterPatchResult, String> {
    let patch_mod_dir = Path::new(&req.user_zomboid_dir)
        .join("mods")
        .join("Z_PZModStudio_MergedPatch");

    // 1. Create patch mod directory structure
    fs::create_dir_all(&patch_mod_dir).map_err(|e| e.to_string())?;

    // 2. Write mod.info manifest
    let mod_info_content = "name=PZ Mod Studio Master Patch\n\
                            id=Z_PZModStudio_MergedPatch\n\
                            description=Auto-generated 3-Way compatibility patch and B42 polyfill layer generated by Project Zomboid Mod Studio.\n\
                            poster=poster.png\n";
    fs::write(patch_mod_dir.join("mod.info"), mod_info_content).map_err(|e| e.to_string())?;

    // 3. Write all merged files (Lua & .txt data scripts)
    let mut files_written = 0;
    for file in &req.merged_files {
        let dest_path = patch_mod_dir.join(&file.relative_path);
        if let Some(parent) = dest_path.parent() {
            fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        fs::write(dest_path, &file.content).map_err(|e| e.to_string())?;
        files_written += 1;
    }

    // 4. Generate & write Z_PZModStudio_Polyfills.lua runtime shim
    let polyfill_dir = patch_mod_dir.join("media").join("lua").join("shared");
    fs::create_dir_all(&polyfill_dir).map_err(|e| e.to_string())?;

    let mut polyfill_lua_content = String::from("-- Z_PZModStudio_Polyfills.lua (PZ Mod Studio Build 42+ Runtime Shim)\n\n");
    polyfill_lua_content.push_str("if not Z_PZModStudio_Polyfills then Z_PZModStudio_Polyfills = {} end\n\n");
    polyfill_lua_content.push_str("function Z_PZModStudio_Polyfills.safeGetText(str)\n");
    polyfill_lua_content.push_str("    if not str then return \"\" end\n");
    polyfill_lua_content.push_str("    local clean = string.gsub(str, \"%%\", \"%%%%\")\n");
    polyfill_lua_content.push_str("    return zombie.core.Translator.getText(clean)\n");
    polyfill_lua_content.push_str("end\n\n");

    let polyfills_count = req.active_polyfill_ids.len();
    fs::write(polyfill_dir.join("Z_PZModStudio_Polyfills.lua"), polyfill_lua_content).map_err(|e| e.to_string())?;

    // 5. Ingame UI Protection Override (Like Avast taking control of Windows Defender!)
    // Overrides in-game ModLoadOrderUI.onAuto so primitive in-game auto-sort is locked and protected
    let client_override_dir = patch_mod_dir.join("media").join("lua").join("client").join("OptionScreens");
    fs::create_dir_all(&client_override_dir).map_err(|e| e.to_string())?;

    let ui_override_content = r#"-- Z_PZModStudio_UIOverride.lua
-- Takes control of in-game auto-sort button to protect PZ Mod Studio Master Patch load order!

Events.OnMainMenuEnter.Add(function()
    print("[PZ Mod Studio] Active: Taking control of load order management.")
    
    if ModLoadOrderUI then
        ModLoadOrderUI.onAuto = function(self)
            local text = "PZ Mod Studio Control Active:\nLoad order is managed automatically by PZ Mod Studio.\nIn-game primitive re-sorting is locked to preserve Master Patch overrides."
            local modal = ISModalDialog:new(0, 0, 420, 160, text, false, nil, nil)
            modal:initialise()
            modal:addToUIManager()
        end
    end
end)
"#;
    fs::write(client_override_dir.join("Z_PZModStudio_UIOverride.lua"), ui_override_content).map_err(|e| e.to_string())?;

    // 6. Update ModListData.ini to place Z_PZModStudio_MergedPatch at the end of load order
    if !req.mod_list_ini_path.is_empty() {
        if let Ok(mut mod_list) = read_mod_list_ini(&req.mod_list_ini_path) {
            let patch_id = "Z_PZModStudio_MergedPatch".to_string();
            mod_list.active_mods.retain(|id| id != &patch_id);
            mod_list.active_mods.push(patch_id);
            let _ = write_mod_list_ini(&req.mod_list_ini_path, &mod_list.active_mods);
        }
    }

    Ok(MasterPatchResult {
        success: true,
        patch_mod_dir: patch_mod_dir.to_string_lossy().to_string(),
        files_written,
        polyfills_injected: polyfills_count,
    })
}
