use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use crate::load_order::ini_parser::{read_mod_list_ini, write_mod_list_ini};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MergedFilePayload {
    pub relative_path: String, // e.g. "media/lua/client/ISUI/ISInventoryPane.lua"
    pub content: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasterPatchRequest {
    pub carrier_workshop_id: Option<String>,
    pub workshop_dir: Option<String>,
    pub pz_install_dir: Option<String>,
    pub user_zomboid_dir: String,
    pub mod_list_ini_path: String,
    pub merged_files: Vec<MergedFilePayload>,
    pub active_polyfill_ids: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MasterPatchResult {
    pub success: bool,
    pub patch_mod_dir: String,
    pub files_written: usize,
    pub polyfills_injected: usize,
}

pub(crate) const VALID_POSTER_PNG: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
    0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x40,
    0x08, 0x06, 0x00, 0x00, 0x00, 0xaa, 0x69, 0x71, 0xde, 0x00, 0x00, 0x00,
    0x39, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0xf8, 0xcf, 0xc0, 0xc0,
    0xc0, 0xc4, 0xc0, 0xc0, 0xc0, 0x04, 0x1d, 0x03, 0x03, 0x03, 0x13, 0x03,
    0x03, 0x03, 0x83, 0xe8, 0x18, 0x18, 0x18, 0x98, 0x18, 0x18, 0x18, 0x18,
    0x43, 0x43, 0x43, 0x03, 0x7d, 0x15, 0x10, 0xc4, 0x65, 0x06, 0x00, 0x80,
    0xa4, 0x3d, 0xd0, 0x32, 0x86, 0x65, 0xa3, 0x00, 0x00, 0x00, 0x00, 0x49,
    0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
];

/// Generates the synthetic master patch mod under Zomboid/mods/Z_PZModStudio_MergedPatch and updates ModListData.ini.
pub fn generate_master_patch(req: MasterPatchRequest) -> Result<MasterPatchResult, String> {
    let mut target_dirs = Vec::new();
    if let (Some(ref carrier_id), Some(ref ws_dir)) = (&req.carrier_workshop_id, &req.workshop_dir) {
        let clean_c = carrier_id.trim();
        if !clean_c.is_empty() && !ws_dir.is_empty() {
            target_dirs.push(Path::new(ws_dir).join(clean_c).join("mods").join("Z_PZModStudio_MergedPatch"));
        }
    }
    if let Some(ref ws_dir) = req.workshop_dir {
        if !ws_dir.is_empty() {
            target_dirs.push(Path::new(ws_dir).join("9999999999").join("mods").join("Z_PZModStudio_MergedPatch"));
        }
    }
    if !req.user_zomboid_dir.is_empty() {
        target_dirs.push(Path::new(&req.user_zomboid_dir).join("mods").join("Z_PZModStudio_MergedPatch"));
        target_dirs.push(Path::new(&req.user_zomboid_dir).join("Lua").join("mods").join("Z_PZModStudio_MergedPatch"));
    }
    if let Some(ref install_dir) = req.pz_install_dir {
        if !install_dir.is_empty() {
            target_dirs.push(Path::new(install_dir).join("mods").join("Z_PZModStudio_MergedPatch"));
        }
    }

    if target_dirs.is_empty() {
        return Err("No valid Zomboid directories provided to generate master patch.".to_string());
    }

    let primary_dir = target_dirs[0].clone();

    let mut mod_info_content = String::new();
    mod_info_content.push_str("name=Z_PZ Mod Studio Master Patch\r\n");
    mod_info_content.push_str("id=Z_PZModStudio_MergedPatch\r\n");
    mod_info_content.push_str("description=Auto-generated 3-Way compatibility patch and polyfill layer generated by Project Zomboid Mod Studio.\r\n");
    mod_info_content.push_str("poster=poster.png\r\n");
    mod_info_content.push_str("icon=icon.png\r\n");
    mod_info_content.push_str("modversion=1.0.0\r\n");
    mod_info_content.push_str("pzversion=41,42\r\n");
    mod_info_content.push_str("author=PZ Mod Studio\r\n");

    let mut files_written = 0;
    let polyfills_count = req.active_polyfill_ids.len();

    let mut polyfill_lua_content = String::from("-- Z_PZModStudio_Polyfills.lua (PZ Mod Studio Build 41/42+ Runtime Shim & Translator Fix)\n\n");
    polyfill_lua_content.push_str("if not Z_PZModStudio_Polyfills then Z_PZModStudio_Polyfills = {} end\n\n");

    polyfill_lua_content.push_str("if zombie and zombie.core and zombie.core.Translator then\n");
    polyfill_lua_content.push_str("    local original_getText = zombie.core.Translator.getText\n");
    polyfill_lua_content.push_str("    zombie.core.Translator.getText = function(str, ...)\n");
    polyfill_lua_content.push_str("        if not str then return \"\" end\n");
    polyfill_lua_content.push_str("        local status, result = pcall(original_getText, str, ...)\n");
    polyfill_lua_content.push_str("        if status and result then return result else return tostring(str) end\n");
    polyfill_lua_content.push_str("    end\n");
    polyfill_lua_content.push_str("end\n\n");

    polyfill_lua_content.push_str("if _G and _G.getText then\n");
    polyfill_lua_content.push_str("    local orig_gt = _G.getText\n");
    polyfill_lua_content.push_str("    _G.getText = function(str, ...)\n");
    polyfill_lua_content.push_str("        if not str then return \"\" end\n");
    polyfill_lua_content.push_str("        local status, result = pcall(orig_gt, str, ...)\n");
    polyfill_lua_content.push_str("        if status and result then return result else return tostring(str) end\n");
    polyfill_lua_content.push_str("    end\n");
    polyfill_lua_content.push_str("end\n\n");

    polyfill_lua_content.push_str("function Z_PZModStudio_Polyfills.safeGetText(str)\n");
    polyfill_lua_content.push_str("    if not str then return \"\" end\n");
    polyfill_lua_content.push_str("    local clean = string.gsub(str, \"%%\", \"%%%%\")\n");
    polyfill_lua_content.push_str("    if zombie and zombie.core and zombie.core.Translator then\n");
    polyfill_lua_content.push_str("        local status, res = pcall(zombie.core.Translator.getText, clean)\n");
    polyfill_lua_content.push_str("        if status and res then return res end\n");
    polyfill_lua_content.push_str("    end\n");
    polyfill_lua_content.push_str("    return tostring(str)\n");
    polyfill_lua_content.push_str("end\n\n");

    let ui_override_content = r#"-- Z_PZModStudio_UIOverride.lua
-- Takes control of in-game auto-sort button to protect PZ Mod Studio Master Patch load order!

Events.OnMainMenuEnter.Add(function()
    print("[PZ Mod Studio] Active: Taking control of load order management.")
    
    if ModLoadOrderUI then
        ModLoadOrderUI.onAuto = function(self)
            local text = "PZ Mod Studio Control Active:\nLoad order is managed automatically by PZ Mod Studio.\nIn-game primitive re-sorting is locked to preserve Master Patch overrides."
            local modal = ISModalDialog:new(0, 0, 420, 160, text, false, nil, nil)
            modal:initialise()
            modal:addToUIManager()
        end
    end
end)
"#;

    for patch_mod_dir in &target_dirs {
        fs::create_dir_all(patch_mod_dir).map_err(|e| e.to_string())?;

        fs::write(patch_mod_dir.join("mod.info"), &mod_info_content).map_err(|e| e.to_string())?;
        let _ = fs::write(patch_mod_dir.join("poster.png"), VALID_POSTER_PNG);
        let _ = fs::write(patch_mod_dir.join("icon.png"), VALID_POSTER_PNG);

        let media_dir = patch_mod_dir.join("media");
        let _ = fs::create_dir_all(&media_dir);
        let _ = fs::write(media_dir.join("mod.info"), &mod_info_content);
        let _ = fs::write(media_dir.join("poster.png"), VALID_POSTER_PNG);
        let _ = fs::write(media_dir.join("icon.png"), VALID_POSTER_PNG);

        for file in &req.merged_files {
            let dest_path = patch_mod_dir.join(&file.relative_path);
            if let Some(parent) = dest_path.parent() {
                fs::create_dir_all(parent).map_err(|e| e.to_string())?;
            }
            fs::write(dest_path, &file.content).map_err(|e| e.to_string())?;
            files_written += 1;
        }

        let polyfill_dir = media_dir.join("lua").join("shared");
        fs::create_dir_all(&polyfill_dir).map_err(|e| e.to_string())?;
        fs::write(polyfill_dir.join("Z_PZModStudio_Polyfills.lua"), &polyfill_lua_content).map_err(|e| e.to_string())?;

        let client_override_dir = media_dir.join("lua").join("client").join("OptionScreens");
        fs::create_dir_all(&client_override_dir).map_err(|e| e.to_string())?;
        fs::write(client_override_dir.join("Z_PZModStudio_UIOverride.lua"), ui_override_content).map_err(|e| e.to_string())?;
    }

    // Update ModListData.ini to place Z_PZModStudio_MergedPatch at the end of load order
    if !req.mod_list_ini_path.is_empty() {
        if let Ok(mut mod_list) = read_mod_list_ini(&req.mod_list_ini_path) {
            let patch_id = "Z_PZModStudio_MergedPatch".to_string();
            mod_list.active_mods.retain(|id| id != &patch_id);
            mod_list.active_mods.push(patch_id);
            let _ = write_mod_list_ini(&req.mod_list_ini_path, &mod_list.active_mods);
        }
    }

    Ok(MasterPatchResult {
        success: true,
        patch_mod_dir: primary_dir.to_string_lossy().to_string(),
        files_written,
        polyfills_injected: polyfills_count,
    })
}

pub fn prepare_carrier_mod(user_zomboid_dir: &str) -> Result<String, String> {
    if user_zomboid_dir.is_empty() {
        return Err("User Zomboid directory path is missing.".to_string());
    }
    let carrier_dir = Path::new(user_zomboid_dir).join("mods").join("Z_PZModStudio_Carrier");
    fs::create_dir_all(&carrier_dir).map_err(|e| e.to_string())?;

    let mod_info = "name=PZ Mod Studio Carrier Patch\r\n\
id=Z_PZModStudio_MergedPatch\r\n\
description=Carrier mod container for PZ Mod Studio 3-Way merges and B42 polyfill shims.\r\n\
poster=poster.png\r\n\
icon=icon.png\r\n\
modversion=1.0.0\r\n\
pzversion=41,42\r\n\
author=PZ Mod Studio\r\n";

    fs::write(carrier_dir.join("mod.info"), mod_info).map_err(|e| e.to_string())?;
    let _ = fs::write(carrier_dir.join("poster.png"), VALID_POSTER_PNG);
    let _ = fs::write(carrier_dir.join("icon.png"), VALID_POSTER_PNG);

    Ok(carrier_dir.to_string_lossy().to_string())
}
